# Generated by Django 4.2 on 2023-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courierID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=100)),
                ('clientSurname', models.CharField(max_length=100)),
                ('dependent', models.CharField(max_length=100)),
                ('orderName', models.CharField(max_length=100)),
                ('conBranch', models.CharField(max_length=100)),
                ('conAddress', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
