# Generated by Django 4.2 on 2023-04-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_courier_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
