# Generated by Django 4.2 on 2023-04-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courierId',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
