# Generated by Django 4.2 on 2023-04-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_api', '0005_remove_order_courierid_delete_sample_delete_courier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courierID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=100)),
                ('clientSurname', models.CharField(max_length=100)),
                ('dependent', models.CharField(max_length=100)),
                ('orderName', models.CharField(max_length=100)),
                ('conBranch', models.CharField(max_length=100)),
                ('conAddress', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('courierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.courier')),
            ],
        ),
    ]
