# Generated by Django 4.2 on 2023-04-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
        migrations.DeleteModel(
            name='Con',
        ),
        migrations.RemoveField(
            model_name='order',
            name='courierID',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
